version: '3'

networks:
  local:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8085:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - local

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5435:${DB_PORT}"
    networks:
      - local
